import Head from 'next/head'
import Image from 'next/image'
import productBundle from 'http://localhost:3001/productBundle.js';

export default function Home() {
  const { Counter } = productBundle;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container mx-auto p-4'>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Counter/>
      </main>

    </div>
  )
}
