import Head from 'next/head'
import productBundle from 'http://localhost:3001/productBundle.js';
import { Suspense } from 'react';

export default function Home() {
  const { Counter, Todo } = productBundle;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container mx-auto p-4'>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Counter />
        <Suspense>
          <Todo/>
        </Suspense>
      </main>

    </div>
  )
}
