import Head from 'next/head'
import productBundle from 'http://localhost:3001/productBundle.js';

export default function Home() {
  const { Counter } = productBundle;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container mx-auto p-4'>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Counter />
        {/* <Todo></Todo> */}
      </main>

    </div>
  )
}
{
  "AWS_ACCOUNT_ID": "471240247400",
  "AWS_ACCOUNT_REGION": "eu-west-2",
  "AWS_ENV_SUFFIX": "dev2",
  "env": "dev2",
  "SINGLESTORE_DB": "devrtap",
  "SINGLESTORE_HOST": "ac5c2dbb6e0824fed8ac5509244728cc-f6f9688e51971a6a.elb.eu-west-1.amazonaws.com",
  "SINGLESTORE_PW": ".<)zopA]nRy~NGc:EZkr",
  "SINGLESTORE_USER": "analytics-store-service"
}
